version: '3'

networks:
  default:
    external: false
  kabacorp:
    external: true

services:
  codechat:
    build:
      dockerfile: Dockerfile
    restart: always
    container_name: codechat
    networks: 
      kabacorp:
        ipv4_address: 172.19.0.4
    tty: true	
    env_file:
      - ./env/.env
    volumes:
      # sudo mkdir -p /data/mongodb
      - ./instances:/home/api/instances
    ports:
      - "8080:8080"
